// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yebsphjbjdtsidykthzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllYnNwaGpiamR0c2lkeWt0aHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjYwMzcsImV4cCI6MjA3MTgwMjAzN30.wDn0YrjJleY5y5VXxaRZvM16ztu63ZNvdRF2S9JAY8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});